name: Build & Test
on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  pr-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: install dependencies
        run: yarn install
      - name : build
        run: yarn build
      - name: run unit tests
        run: yarn unit-test