name: Publish to NPM
on:
  push:
    branches:
      - main
jobs:
  publish-to-npm:
    runs-on: ubuntu-latest
    steps:
      - name: check out repository code
        uses: actions/checkout@v4
      - name: publish to npm
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - run: |
          cat package.json | sed 's/"version": "1.0.0"/"version":"1.0.$GITHUB_RUN_NUMBER"/' > package.json.new
          rm package.json
          mv package.json.new package.json
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}