name: Publish to NPM
run-name: ${{ github.actor }} is publishing ts-chan package to NPM
on:
  push:
    branches:
      - main
jobs:
  publish-to-npm:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Publish to NPM
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
          npm publish